### ISSUE TITLE
ATP add user: text for form validation states [TFS 36537]

### ISSUE THREAD

**Issue by dreeeeewwwww** [USAJOBS/ATP-Support#101]
https://opm.invisionapp.com/share/Q8OESMCYS5P#/220162877_Team_Members

When adding a user to an review board, we need text for the following input validation state:

- [ ] This is not a valid federal/.gov address.
- [ ] This address is not a member of the community. Plz add this user in open opps/contact your open opps manager.

**Comment by dalenard21** [comment]
@dreeeeewwwww I'm not sure if I fully understand the use case here or if I have the message 'right', so let's discuss my options below:

**Not a valid federal email address**
The email address you entered is not a valid federal email address.  You can only add members to this board if they're a current federal employee with a valid federal email address.

**Not a current member of the community**
We can't add this user to the board, because the email address isn't associated with an existing member of this community.  You need to first add this user as a member of the community in Open Opportunities. Contact your Open Opportunities Community Manager for help.

Thoughts?

**Comment by dalenard21** [comment]
@dreeeeewwwww Here's a shorter message.

**Not a current member of the community**
We can't add this user, because they're not a member of this Open Opportunities community. Contact your Open Opportunities Community Manager for help.

**Comment by dreeeeewwwww** [comment]
@jonwoody Tagging you here with updated text for the ATP invite user validation ticket:

**Validation state: Not a federal email address**
The email address you entered is not a valid federal email address. You can only add members to this board if they're a current federal employee with a valid federal email address.

**Validation state: Not a current member of the community**
We can't add this user, because they're not a member of this Open Opportunities community. Contact your Open Opportunities Community Manager for help.

**Comment by dalenard21** [comment]
@Piglady64 just adding you to this issue incase any content questions come up.  But, I believe this is in development.

**Comment by dalenard21** [comment]
@jonwoody - do you know if these changes went out with the release today?  I'm not sure which TFS tickets these relate to.

**Comment by jonwoody** [comment]
@dalenard21 In speaking with Dan T, this is related to PBI 36537 and should be released today 6/19/19. Would you like me to close or do you want to do that? (I don't want to close this out without you knowing)

**Comment by dalenard21** [comment]
Thanks @jonwoody I'm going to close this issue.  If any changes need to be made, we'll just open a new github issue.  thanks.
