### ISSUE TITLE
Clarify language for USAJOBs sign on

### ISSUE THREAD

**Issue by starrchen** [USAJOBS/ATP-Support#27]
We received feedback that the USAJOBs sign in helper text does not make it clear that it's for ATP, so folks could mistakenly end up using their job seeker login credentials when they see "USAJOBS users" instead. It was requested that the messaging here be changed so as to avoid this.

![image.png](https://images.zenhubusercontent.com/5ba2602c3fd1d02b91c1adbd/9ba62a89-d176-43ee-8062-e463b15ed70c)

**Comment by dalenard21** [comment]
Hi @starrchen -

Okay. My original content that I provided to Drew and Matt included a lead in sentence that said:

"Sign into the Agency Talent Portal using your USAJOBS or USA Staffing account."  this would appear above the two sign in options. Also, the header includes "Agency Talent Portal", so I think if you add the sentence above it will be clear they're signing into ATP.

But, I don't understand what you mean by users mistakingly using their USAJOBS sign in credentials.  I thought they could sign into ATP using their USAJOBS email address and password.  Is that not true?

**Comment by Piglady64** [comment]
Users set up an ATP account it is not tied to a USAJOBS account since these are agencies using the product and not job seekers.

**Comment by dalenard21** [comment]
Thanks @Piglady64 

@starrchen Julie explained in more detail. I misunderstood how this all works. I'll get you updated content tomorrow.

**Comment by dalenard21** [comment]
@starrchen @dreeeeewwwww @Piglady64 

Here's some revised content for the main sign in screen:

Sign In
Choose a system to use to sign into the Agency Talent Portal.

USAJOBS
Sign in using your USAJOBS recruiter account.  
Need an account?  Contact your agency administrator or email recruiter-help@usajobs.gov.

USA Staffing
Sign in using your USA Staffing account.


I think we should add "Need an account" on this initial screen.  BUT, I'm not sure what the process is for getting a USA Staffing account?  It would be good if we can have that option as well.

**Comment by dreeeeewwwww** [comment]
<img width="752" alt="screen shot 2018-10-22 at 3 02 56 pm" src="https://user-images.githubusercontent.com/13023132/47312914-9b1aa880-d60b-11e8-84b7-a5c7e1ffbce3.png">

@dalenard21 I made the above text changes on my localhost, wanted to double check if you wanted to leave the descriptive text as-is under the USAS sign in ("For HR Specialists and Hiring Managers. Sign in using your USA Staffing email and password or CAC card.") before I pushed up the changes.

**Comment by Piglady64** [comment]
I am not sure users will understand "recruiter account". When Lauren does her demos she consistently uses ATP and when I get inquiries I tell them to request and Agency Talent Portal account. Also, the header says  "USAJOBS Agency Talent Portal".

**Comment by Piglady64** [comment]
For USA Staffing do we need to be more specific by saying something like "For HR Specialists and Hiring Managers who currently use USA Staffing..." because all of them are HR Specialists, Hiring Managers and Recruiters that use this system.  They should know what Talent Acquisition System they use but will those not using Staffing wonder how they get a USA Staffing email?

**Comment by Piglady64** [comment]
Since you are saying "Choose a system to use to sign into the Agency Talent Portal (add (ATP))" then say Sign in using your USAJOBS ATP account.

**Comment by dalenard21** [comment]
@Piglady64 @dreeeeewwwww 

Let's take Julie's suggestion and change the "Sign in using your USAJOBS ATP account".  Because if that's how users know it, we should use their language.

For the USA Staffing, can we just say "Sign in using your USA Staffing account"?  I say we take out "For HR Specialists and Hiring Managers", because don't users in those roles also go through USAJOBS?

Finally, if there is a way to request a USA Staffing account, then I think we should include that information. But I don't know how to request.  

Let's review this with Brody and team too, because I want to make sure this all makes sense.

Thanks
Debbie

**Comment by dalenard21** [comment]
@dreeeeewwwww 

One more suggestion for the USA Staffing button.  Let's use this description:

**Sign in using your USA Staffing account**
If you're a current USA Staffing customer, sign in using your USA Staffing email and password or CAC card.
