### ISSUE TITLE
Email validation - need content

### ISSUE THREAD

**Issue by dalenard21** [USAJOBS/ATP-Support#53]
TFS Ticket 35055 Email Validation

As a potential user, I want an email sent to the email address that I register with so that my control of the email account can be validated.

This email is sent once a user submits a new user form in ATP.  The email contains a button / link to confirm the information:

**Comment by dalenard21** [comment]
@abudz19 here's a first draft of the email validation for a new ATP user.  Please review to make sure I have the right intent of the message, etc.

[ATP-email-validation_20190103.docx](https://github.com/USAJOBS/ATP-Support/files/2724743/ATP-email-validation_20190103.docx)

**Comment by abudz19** [comment]
@dalenard21 
Two things: 

1. can we add 'address' onto the end of the subject line and also Change 'Click the link' to 'Click the button'?
2. Should we add language that indicates what will happen next? Something like, 'after you have confirmed your email address, your agency's user administrator will review your account request.'

I think the ATP team refers the to "agency user administrator" as just the "agency administrator," so if you can think of a better or different way to refer to this person happy for any suggestions. 
Otherwise it looks great!

**Comment by dalenard21** [comment]
@abudz19 here's an updated version.
[ATP-email-validation_v2_20190104.docx](https://github.com/USAJOBS/ATP-Support/files/2727569/ATP-email-validation_v2_20190104.docx)
