### ISSUE TITLE
ATP: New user email - user validation [TFS 35056]

### ISSUE THREAD

**Issue by dreeeeewwwww** [USAJOBS/ATP-Support#71]
## From TFS

As an Agency Admin or Recruiter-Help, I want an email sent to me when a new user requests access and has validated their email.

After a new user requests access and the user has validated their email, an automatic email is sent to the agency admin or recruiter-help containing the following:

**Email subject line:**
```
Please confirm new ATP user
```

**Email content:**

```
Hello [Agency Admin name or Recruiter-help],

The following new user has requested an account with the USAJOBS Agency Talent Portal. Please review their information to approve a new account.

<Insert new user information>

<Include button/link label “Yes, approve a new account”>

<Include button/link label “No, don’t approve a new account”>

Thanks,
The USAJOBS Agency Talent Portal Team
```

**Comment by KatMullens-work** [comment]
Link to this item's TFS issue: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems/edit/35056

As of 2/6/19, per Drew there is not a design for this item yet.

**Comment by dalenard21** [comment]
@dreeeeewwwww - yes this content is correct.  I've attached the original word doc.
[ATP-user-validation-email_20190103.docx](https://github.com/USAJOBS/ATP-Support/files/2841524/ATP-user-validation-email_20190103.docx)

**Comment by KatMullens-work** [comment]
Updated AC:

Once the user verifies their email using the button/link in 35055, the account validation email is sent to the agency admin or recruiter help (if no agency admin is listed for that user) containing the new user's info. It also contains a link that an agency admin/recruiter help can click on in order to grant default access to the user (general role). 
- If this link is clicked, the user is sent an email to verify that access has been granted (need to link to this email). 
- The email will also include a "Deny" link that will not grant access, and will in-turn send an email to the requesting user. This click will also register a comment on the user's account.):

Email subject line: Please confirm new ATP user
Email content:
Hello [Agency Admin name or Recruiter-help],
The following new user has requested an account with the USAJOBS Agency Talent Portal (ATP). Please review their information to approve a new account.
<Insert new user information>
<Include button/link label “Yes, approve a new account”>
<Include button/link label “No, don’t approve a new account”>
 
Thanks,
The USAJOBS Agency Talent Portal Team

**Comment by KatMullens-work** [comment]
Hi @dalenard21 : 

What does 
<Insert new user information>
in the email consist of?

Thanks, 
kat

**Comment by KatMullens-work** [comment]
Accurate AC as of this date/time: 
Once the user verifies their email using the button/link in 35055, the account validation email is sent to the agency admin or recruiter help (if no agency admin is listed for that user) containing direction to log in to ATP to view a new access request and decide to accept or decline it. 
-If the Approve option link is clicked, the user is sent an email to verify that access has been granted (need to link to this email):  https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems/edit/35058
- The email will also include a "Deny" link that will not grant access, and will in-turn send an email to the requesting user. This click will also register a comment on the user's account.): https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems/edit/35057

Email subject line: Please confirm new ATP user
Email content:
Hello [Agency Admin name or Recruiter-help],

A new user has requested an account with the USAJOBS Agency Talent Portal (ATP). Please review their information and decide if you wish to approve this new account within ATP.

Click on this link to go to ATP (if you're not logged in to ATP, you'll be led to the login page first); if this link does not work, please copy and paste the entire link into your browser: <insert link to user validation page>
 
Thanks,
The USAJOBS Agency Talent Portal Team

**Comment by dalenard21** [comment]
@KatMullens-work 

I noticed the content you have in the most recent update is different than the content I provided in the word doc.  Was there a discussion about changing the content?  Perhaps the design of the email  impacted the messaging, but I'd like to revisit the content.

CC: @dreeeeewwwww

**Comment by KatMullens-work** [comment]
I’m not sure what you mean or believe I should do here. Could you please be more explicit? I capture the content for any tickets at the moment they were created. I was not notified of content updates so if they are required, someone would need to tell me that. Does that help?


On Mar 20, 2019, at 5:37 PM, dalenard21 <notifications@github.com<mailto:notifications@github.com>> wrote:


@KatMullens-work<https://github.com/KatMullens-work>

I noticed the content you have in the most recent update is different than the content I provided in the word doc. Was there a discussion about changing the content? Perhaps the design of the email impacted the messaging, but I'd like to revisit the content.

CC: @dreeeeewwwww<https://github.com/dreeeeewwwww>

**Comment by dalenard21** [comment]
@KatMullens-work 

It's probably just a mix up.  I added a word document to this GitHub issue with content for this email on Feb. 7. And, looks like you added that content to the AC on Feb. 7 too.  But, then on Feb. 9 there's another update and the content is different.  I just want to make sure we have the right content and could easily be that someone else gave you content not knowing that we already had some.  Or, maybe it changed because they couldn't do the buttons?

I'll follow up with @dreeeeewwwww to make sure I understand what needs to happen in this email and will update this with the right message.

**Comment by dalenard21** [comment]
@KatMullens-work just spoke to @dreeeeewwwww and this is on the backlog. He just started working on this entire process, so let's just hold on this until he has a design ready.

**Comment by KatMullens-work** [comment]
Okay I’ll hold off until told to reengage. Thanks!

**Comment by dalenard21** [comment]
@Piglady64 here's another one. Don't know status, but in case there's a question about content.

**Comment by dalenard21** [comment]
Per @jdstill on slack, this issue can be closed.
